name: Store Update

on:
  workflow_dispatch:   # allow manual + API triggered runs

jobs:
  store-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
          pip install notion-client python-dotenv

      - name: Run Store_update script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          STORE_GAMES_ID: ${{ secrets.STORE_GAMES_ID }}
          MAIN_DB_ID: ${{ secrets.MAIN_DB_ID }}
        run: |
          python scripts/Games_update.py   
